# Generated by Django 5.0.6 on 2024-07-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('student_count', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyStudentStat',
        ),
    ]
