# Generated by Django 5.0.6 on 2024-07-11 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_historicaluser_role_alter_user_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
