# Generated by Django 5.0.6 on 2024-07-16 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_graduatedstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduatedstudent',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
