# Generated by Django 5.0.6 on 2024-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_graduatedstudent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystat',
            name='graduated_count',
            field=models.IntegerField(default=0),
        ),
    ]
