# Generated by Django 5.0.6 on 2024-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dailystat_graduated_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystat',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='graduatedstudent',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
